name: Actions Workflow

on:
  push:
    paths:
      - "**.go"

jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: make docker image
        run: |
          docker stop httpserver
          docker rm httpserver
          docker rmi httpserver/https
          docker build -t httpserver/https .
      - name: make docker container
        run: |
          docker run --name httpserver -d -p 80:80 -p 443:443 -v  cert-cache:/cert-cache  -v $(pwd)/target:/static    httpserver/https
