name: Actions Workflow

on:
  push:
    paths:
      - "**.go"

jobs:
  run-backend-workflow:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: clean running container if any
        run: |
          if [ ! "$(docker ps -q -f name=httpserver)" ]; then
            if [ "$(docker ps -aq -f status=exited -f name=httpserver)" ]; then
              docker rm httpserver
              docker rmi httpserver/https
            fi
          fi
      - name: make docker image
        run: |
          docker build -t httpserver/https .
      - name: make docker container
        run: |
          docker run --name httpserver -d -p 80:80 -p 443:443 -v  cert-cache:/cert-cache  -v $(pwd)/target:/static    httpserver/https
