name: Actions Workflow

on:
  push:
    paths:
      - "**.go"

jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: clean running container if any
        run: |
          docker stop httpserver 2>/dev/null
          docker rm httpserver 2>/dev/null
          docker rmi httpserver/https 2>/dev/null
      - name: make docker image
        run: |
          docker build -t httpserver/https .
      - name: make docker container
        run: |
          docker run --name httpserver -d -p 80:80 -p 443:443 -v  cert-cache:/cert-cache  -v $(pwd)/target:/static    httpserver/https
