name: Actions Workflow

on:
  push:
    paths:
      - "**.go"

jobs:
  run-backend-workflow:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: clean running httpserver container if any
        run: |
          containerID="$(docker ps -q -f name=httpserver)"
          if [ -n containerID ]; then
              echo "masalah1"          
              docker stop httpserver
              echo "masalah2"              
              docker rm httpserver
              docker rmi httpserver/https
          fi
          echo "masallah3"
      - name: make docker image
        run: |
          docker build -t httpserver/https .
      - name: make docker container
        run: |
          docker run --name httpserver -d -p 80:80 -p 443:443 -v  cert-cache:/cert-cache  -v $(pwd)/target:/static    httpserver/https
