name: Actions Workflow

on:
  push:
    branches:
      - master

jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: make docker image
        run: |
          docker build -t httpserver/https .
      - name: make docker container
        run: |
          docker run -d -p 80:80 -p 443:443 -v  cert-cache:/cert-cache  -v $(pwd)/target:/static    httpserver/https
      - name: List Files
        run: |
          pwd
          ls
