name: Actions Workflow

on:
  push:
    branches:
      - master

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls ~
