name: Actions Workflow

on:
  push:
    branches:
      - master

jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: List Files
        run: |
          docker images
          pwd
          ls ~
